spring.application.name=IPLAuctionDashboard
spring.datasource.url=jdbc:postgresql://localhost:5432/kevin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=kevin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
<<<<<<< HEAD
=======
logging.file.name =/Users/kevin/logs/ipl-auction.log
logging.level.root=INFO
>>>>>>> 20c731ae8dec05f537f7558445f117bb9764e7f6
