spring.application.name=IPLAuctionDashboard
spring.datasource.url=jdbc:postgresql://localhost:5432/kevin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=kevin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
<<<<<<< HEAD
=======
logging.file.name =/home/jmkevin2006/logs/api/ipl-auction/ipl-auction.log
logging.level.root=INFO
logging.pattern.console=
server.port=8080
>>>>>>> 20c731ae8dec05f537f7558445f117bb9764e7f6
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain
server.compression.min-response-size=1024
